<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MenusSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id_menu' => 6,
                'kode_menu' => '1',
                'kode_induk' => '0',
                'nama' => 'Dashboard',
                'link' => 'dashboard/load',
                'icon' => 'bi-house',
                'sort_order' => 1,
            ],
            [
                'id_menu' => 9,
                'kode_menu' => '3',
                'kode_induk' => '0',
                'nama' => 'Pengumuman',
                'link' => 'pengumuman',
                'icon' => 'bi-megaphone',
                'sort_order' => 3,
            ],
            [
                'id_menu' => 10,
                'kode_menu' => '4',
                'kode_induk' => '0',
                'nama' => 'Halaman',
                'link' => 'pages',
                'icon' => 'bi-file-text',
                'sort_order' => 4,
            ],
            [
                'id_menu' => 11,
                'kode_menu' => '9',
                'kode_induk' => '0',
                'nama' => 'Tampilan',
                'link' => '#',
                'icon' => 'bi-display',
                'sort_order' => 9,
            ],
            [
                'id_menu' => 12,
                'kode_menu' => '9.1',
                'kode_induk' => '9',
                'nama' => 'Menu',
                'link' => 'navbar',
                'icon' => 'bi-three-dots-vertical',
                'sort_order' => 10,
            ],
            [
                'id_menu' => 13,
                'kode_menu' => '9.3',
                'kode_induk' => '9',
                'nama' => 'Slider',
                'link' => 'hero',
                'icon' => 'bi-three-dots-vertical',
                'sort_order' => 12,
            ],
            [
                'id_menu' => 14,
                'kode_menu' => '9.5',
                'kode_induk' => '9',
                'nama' => 'Layanan',
                'link' => 'mitra',
                'icon' => 'bi-three-dots-vertical',
                'sort_order' => 14,
            ],
            [
                'id_menu' => 15,
                'kode_menu' => '9.4',
                'kode_induk' => '9',
                'nama' => 'Informasi',
                'link' => 'konfigurasi',
                'icon' => 'bi-three-dots-vertical',
                'sort_order' => 13,
            ],
            [
                'id_menu' => 16,
                'kode_menu' => '9.2',
                'kode_induk' => '9',
                'nama' => 'Sosial',
                'link' => 'sosmed',
                'icon' => 'bi-three-dots-vertical',
                'sort_order' => 11,
            ],
            [
                'id_menu' => 17,
                'kode_menu' => '11',
                'kode_induk' => '0',
                'nama' => 'Urutan Tampilan',
                'link' => 'layout',
                'icon' => 'bi-layout-text-window',
                'sort_order' => 19,
            ],
            [
                'id_menu' => 18,
                'kode_menu' => '12',
                'kode_induk' => '0',
                'nama' => 'Pengaturan',
                'link' => '#',
                'icon' => 'bi-gear',
                'sort_order' => 20,
            ],
            [
                'id_menu' => 19,
                'kode_menu' => '12.1',
                'kode_induk' => '12',
                'nama' => 'Pengguna',
                'link' => 'user',
                'icon' => 'bi-person',
                'sort_order' => 21,
            ],
            [
                'id_menu' => 20,
                'kode_menu' => '12.3',
                'kode_induk' => '12',
                'nama' => 'Role',
                'link' => 'role',
                'icon' => 'bi-shield-lock',
                'sort_order' => 23,
            ],
            [
                'id_menu' => 21,
                'kode_menu' => '12.2',
                'kode_induk' => '12',
                'nama' => 'Otoritas',
                'link' => 'otoritas',
                'icon' => 'bi-shield-check',
                'sort_order' => 22,
            ],
            [
                'id_menu' => 23,
                'kode_menu' => '12.4',
                'kode_induk' => '12',
                'nama' => 'Menu ',
                'link' => 'menu',
                'icon' => 'bi-people',
                'sort_order' => 24,
            ],
            [
                'id_menu' => 24,
                'kode_menu' => '2',
                'kode_induk' => '0',
                'nama' => 'Berita',
                'link' => 'posts',
                'icon' => 'bi-newspaper',
                'sort_order' => 2,
            ],
            [
                'id_menu' => 28,
                'kode_menu' => '9.6',
                'kode_induk' => '9',
                'nama' => 'Team',
                'link' => 'team',
                'icon' => 'bi-three-dots-vertical',
                'sort_order' => 15,
            ],
            [
                'id_menu' => 31,
                'kode_menu' => '10.2',
                'kode_induk' => '10',
                'nama' => 'Motif',
                'link' => 'motif',
                'icon' => 'bi bi-receipt',
                'sort_order' => 18,
            ],
            [
                'id_menu' => 32,
                'kode_menu' => '10',
                'kode_induk' => '0',
                'nama' => 'Data Master',
                'link' => '#',
                'icon' => 'bi bi-receipt',
                'sort_order' => 16,
            ],
            [
                'id_menu' => 33,
                'kode_menu' => '10.1',
                'kode_induk' => '10',
                'nama' => 'Kategori',
                'link' => 'categories',
                'icon' => 'bi-file-text',
                'sort_order' => 17,
            ],
            [
                'id_menu' => 39,
                'kode_menu' => '5',
                'kode_induk' => '0',
                'nama' => 'Berkas',
                'link' => 'berkas',
                'icon' => 'bi-file-text',
                'sort_order' => 5,
            ],
            [
                'id_menu' => 45,
                'kode_menu' => '8',
                'kode_induk' => '0',
                'nama' => 'Personel',
                'link' => 'personel',
                'icon' => 'bi bi-person',
                'sort_order' => 8,
            ],
            [
                'id_menu' => 46,
                'kode_menu' => '6',
                'kode_induk' => '0',
                'nama' => 'Folder',
                'link' => 'folder',
                'icon' => 'bi bi-folder',
                'sort_order' => 6,
            ],
            [
                'id_menu' => 47,
                'kode_menu' => '7',
                'kode_induk' => '0',
                'nama' => 'Dokumen Akreditasi',
                'link' => 'dokumen',
                'icon' => 'bi bi-folder',
                'sort_order' => 7,
            ]
        ];

        $this->db->table('menus')->insertBatch($data);
    }
}
