<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class PersonelSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id_personel'    => 39,
                'nama'           => 'Tester 5',
                'jabatan'        => 'Anggota kop',
                'penempatan'     => 'Lab Udara(PPLH)',
                'foto'           => '1757171183c361da5b8d.jpg',
                'nip'            => '311212321',
                'tempat_lahir'   => 'Banjarbaru',
                'tanggal_lahir'  => '2025-09-05',
                'jenis_kelamin'  => 'Perempuan',
                'kebangsaan'     => 'Indonesia',
                'alamat'         => 'Jl. apalahaaa',
                'no_handphone'   => '089876112312',
                'email'          => 'salsa@gmail.com',
                'doc_cv'         => NULL,
                'doc_coc'        => NULL,
                'doc_surat_tugas'=> NULL,
                'doc_lainnya'    => '["1757230600597a23a5b2.pdf"]',
                'urutan'         => 1,
                'status'         => 'Y',
            ],
            [
                'id_personel'    => 48,
                'nama'           => 'Tester 3',
                'jabatan'        => 'Anggota',
                'penempatan'     => 'Lab Kualitas Air',
                'foto'           => '17571702064bb4c71dd8.jpg',
                'nip'            => '12133523642',
                'tempat_lahir'   => 'Banjarbaru',
                'tanggal_lahir'  => '2025-08-13',
                'jenis_kelamin'  => 'Perempuan',
                'kebangsaan'     => 'Indonesia',
                'alamat'         => 'Jl. taparani',
                'no_handphone'   => '21313412',
                'email'          => 'mahes@gmail.com',
                'doc_cv'         => NULL,
                'doc_coc'        => '1757170060139ccd7339.pdf',
                'doc_surat_tugas'=> NULL,
                'doc_lainnya'    => NULL,
                'urutan'         => 3,
                'status'         => 'Y',
            ],
            [
                'id_personel'    => 49,
                'nama'           => 'Tester 1',
                'jabatan'        => 'Kepala LAB',
                'penempatan'     => 'Lab Struktur dan Material',
                'foto'           => '17565601778fdc4b28da.png',
                'nip'            => '231231231231231',
                'tempat_lahir'   => 'Banjarbaru',
                'tanggal_lahir'  => '2025-08-19',
                'jenis_kelamin'  => 'Laki-laki',
                'kebangsaan'     => 'Indonesia',
                'alamat'         => 'sadasd',
                'no_handphone'   => '123124234',
                'email'          => 'dwdasd@gmsda.com',
                'doc_cv'         => NULL,
                'doc_coc'        => NULL,
                'doc_surat_tugas'=> NULL,
                'doc_lainnya'    => NULL,
                'urutan'         => 2,
                'status'         => 'Y',
            ],
            [
                'id_personel'    => 88,
                'nama'           => 'dsfsdf',
                'jabatan'        => 'sdasda',
                'penempatan'     => 'Lab Tanah',
                'foto'           => '1757173499c68bb9c625.png',
                'nip'            => '23423',
                'tempat_lahir'   => 'TANAH LAUT',
                'tanggal_lahir'  => '2025-09-24',
                'jenis_kelamin'  => 'Laki-laki',
                'kebangsaan'     => 'Indonesia',
                'alamat'         => 'asdasd',
                'no_handphone'   => '123231',
                'email'          => 'user@gmssaail.com',
                'doc_cv'         => NULL,
                'doc_coc'        => NULL,
                'doc_surat_tugas'=> NULL,
                'doc_lainnya'    => NULL,
                'urutan'         => 4,
                'status'         => 'Y',
            ],
            [
                'id_personel'    => 90,
                'nama'           => 'adasd',
                'jabatan'        => 'koor lapangan',
                'penempatan'     => 'Mutu dan Administrasi',
                'foto'           => '1757173984354408dc10.jpg',
                'nip'            => '122',
                'tempat_lahir'   => 'TANAH LAUT',
                'tanggal_lahir'  => '2025-09-18',
                'jenis_kelamin'  => 'Perempuan',
                'kebangsaan'     => 'Indonesia',
                'alamat'         => 'sadsda',
                'no_handphone'   => '23123',
                'email'          => 'dwdasd@gsmsda.com',
                'doc_cv'         => NULL,
                'doc_coc'        => '17571739849f38a789e1.pdf',
                'doc_surat_tugas'=> NULL,
                'doc_lainnya'    => NULL,
                'urutan'         => 6,
                'status'         => 'Y',
            ],
            [
                'id_personel'    => 325,
                'nama'           => 'Riyan',
                'jabatan'        => 'Anggota kop',
                'penempatan'     => 'Lab Tanah',
                'foto'           => '1757335591e3acd5c5b1.jpg',
                'nip'            => '212',
                'tempat_lahir'   => 'sdas',
                'tanggal_lahir'  => '2025-09-04',
                'jenis_kelamin'  => 'Laki-laki',
                'kebangsaan'     => 'Indonesia',
                'alamat'         => 'asdasd',
                'no_handphone'   => '321423',
                'email'          => 'admin@com.comasdasd',
                'doc_cv'         => '1757335591ad852e1c2c.pdf',
                'doc_coc'        => '175733559109ca588e98.pdf',
                'doc_surat_tugas'=> NULL,
                'doc_lainnya'    => '["17573355916d3de49ad7.pdf"]',
                'urutan'         => 7,
                'status'         => 'Y',
            ],
            [
                'id_personel'    => 326,
                'nama'           => 'Lidan',
                'jabatan'        => 'sadas',
                'penempatan'     => 'Mutu dan Administrasi',
                'foto'           => '175746828904b3699773.png',
                'nip'            => '234123',
                'tempat_lahir'   => 'sdas',
                'tanggal_lahir'  => '2025-09-12',
                'jenis_kelamin'  => 'Laki-laki',
                'kebangsaan'     => 'Indonesia',
                'alamat'         => 'sadas',
                'no_handphone'   => '12321',
                'email'          => 'test@gmail.comasda',
                'doc_cv'         => '175746832274b3c3499f.pdf',
                'doc_coc'        => '175746832278871dae7b.pdf',
                'doc_surat_tugas'=> NULL,
                'doc_lainnya'    => '["17574683225b10d596bc.pdf","17574683226084ea35ec.pdf"]',
                'urutan'         => 5,
                'status'         => 'Y',
            ],
            [
                'id_personel'    => 327,
                'nama'           => 'Senior',
                'jabatan'        => 'gigabite',
                'penempatan'     => 'Mutu dan Administrasi',
                'foto'           => '17576822369ee3d53742.png',
                'nip'            => '212',
                'tempat_lahir'   => 'asdasd',
                'tanggal_lahir'  => '2025-09-02',
                'jenis_kelamin'  => 'Perempuan',
                'kebangsaan'     => 'Indonesia',
                'alamat'         => 'xsczxcz',
                'no_handphone'   => '2342',
                'email'          => '34234@gmail.comsd32e',
                'doc_cv'         => NULL,
                'doc_coc'        => NULL,
                'doc_surat_tugas'=> NULL,
                'doc_lainnya'    => NULL,
                'urutan'         => 8,
                'status'         => 'Y',
            ],
            [
                'id_personel'    => 328,
                'nama'           => '2311016210012',
                'jabatan'        => 'Software Engineering Lead',
                'penempatan'     => 'Lab Kualitas Air',
                'foto'           => '1757682490c048f0b425.jpeg',
                'nip'            => '12345678910',
                'tempat_lahir'   => 'Jakarta',
                'tanggal_lahir'  => '2025-09-04',
                'jenis_kelamin'  => 'Perempuan',
                'kebangsaan'     => 'Indonesia',
                'alamat'         => 'JALAN TANJUNG SELATAN DUA BLOK D',
                'no_handphone'   => '08125176391',
                'email'          => 'rezkyaulia907@gmail.com',
                'doc_cv'         => NULL,
                'doc_coc'        => NULL,
                'doc_surat_tugas'=> NULL,
                'doc_lainnya'    => NULL,
                'urutan'         => 9,
                'status'         => 'Y',
            ],
        ];

        $this->db->table('personel')->insertBatch($data);
    }
}
